version: 2

jobs:
  build:
    working_directory: ~/context-webclient
    docker: 
      - image: circleci/node:6.10.2
    filters:
      branches:
        only: master
    steps:
      - checkout
      - run:
          name: clean the cache
          command: npm cache clean
      - run:
          name: install npm dependencies
          command: npm install
      - run:
          name: install netlify globally
          command:  npm install netlify-cli -g
      - run:
          name: install wait-on globally
          command: npm install wait-on -g
      # local host will access production server
      - run:
          name: ready test environment
          command: npm run ci-start
      # Wait on app to be ready
      - run:
          name: wait-on test environment to be ready
          command: wait-on http://localhost:3000
      # Run Cypress tests
      - run:
          name: run e2e tests
          command: npm test
      # Build production site
      - run:
          name: production-build
          command: npm run production-build
      # Deploy to netlify
      - run:
          name: deploy-to-netlify
          command: netlify deploy -s $NETLIFY_SITE_ID -t $NETLIFY_ACCESS_TOKEN -p ./dist      

 
